create procedure -- JHM
"_SRM"."ServiceRequestItemDetails"( 
  in @RowId char(1024) default null,
  in @Base64Encode bit default 0 ) 
result( 
  "RowId" char(1024),
  "ServiceRequestId" integer,
  "ServiceRequestParentId" integer,
  "OriginalServiceRequestId" integer,
  "ServiceRequestNestedLevel" tinyint,
  "ServiceRequestExternalId" char(20),
  "ServiceRequestType" char(10),
  "TitleBarDisplay" char(128),
  "ServiceRequestDate" date,
  "ServiceRequestOriginator" integer,
  "OfficeCodeId" integer,
  "OfficeCode" char(10),
  "AssignedToUserId" integer,
  "AssignedToUserFullName" char(256),
  "ServiceRequestStatus" char(25),
  "ServiceRequestPriority" tinyint,
  "ServiceRequestPriorityDisplay" char(25),
  "ServiceRequestTitle" char(128),
  "ServiceRequestPrelimDueDate" date,
  "ServiceRequestFinalDueDate" date,
  "PlannedStartDate" date,
  "PlannedEndDate" date,
  "PercentComplete" integer,
  "PercentHoursComplete" integer,
  "PercentTimeComplete" integer,
  "EstimatedRemainingHours" numeric(12,2),
  "ActualHoursWorked" numeric(12,2),
  "EstimatedTotalHours" numeric(12,2),
  "MandatoryMinReportDays" integer,
  "TransaltNumber" char(25),
  "TransaltId" integer,
  "PrimaryPOCID" integer,
  "PrimaryPOCName" char(256),
  "PrimaryPOCEmail" varchar(500),
  "PrimaryPOCPhone" char(20),
  "AltPOCID" integer,
  "AltPOCName" char(256),
  "AltPOCEmail" varchar(500),
  "AltPOCPhone" char(20),
  "ServiceRequestDeliverables" long varchar,
  "ServiceRequestCategories" long varchar,
  "ServiceRequestRequiredApprovals" long varchar,
  "ServiceRequestRequiredDetails" long varchar,
  "VesselIds" long varchar,
  "VesselNames" long varchar,
  "ServiceRequestParentExternalId" char(20),
  "OriginalServiceRequestExternalId" char(20),
  "CanEditDescription" bit,
  "CanEditStatus" bit,
  "CanAddSupportItem" bit,
  "CanEditProgress" bit,
  "CanEditAttachment" bit,
  "CanEditMilestones" bit,
  "CanEditUserProfile" bit,
  "CanEditBranchProfile" bit,
  "CanEditTeamSpace" bit,
  "LastMileStone" char(80),
  "ActiveSequenceNumber" tinyint,
  "NumberOfAttachments" integer,
  "NumberOfRelatedItems" integer,
  "OfficeCodeDisplay" char(128),
  "TitleIsEditable" bit,
  "PrimaryPOCIsEditable" bit,
  "AlternatePOCIsEditable" bit,
  "CategoryIsEditable" bit,
  "InvolvementIsEditable" bit,
  "DeliverablesAreEditable" bit,
  "RequiredApprovalsAreEditable" bit,
  "VesselsAreEditable" bit,
  "TransaltNumberIsEditable" bit,
  "PreliminaryDueDateIsEditable" bit,
  "FinalDueDateIsEditable" bit,
  "EstimatedTotalHoursAreEditable" bit,
  "MandatoryMinReportDaysAreEditable" bit,
  "OfficeCodeIdIsEditable" bit,
  "AssignedToUserIsEditable" bit,
  "PriorityIsEditable" bit,
  "EstimatedRemainingHoursAreEditable" bit,
  "ActualHoursWorkedAreEditable" bit,
  "PercentHoursCompleteIsEditable" bit,
  "PercentWorkCompleteIsEditable" bit,
  "PlannedStartDateIsEditable" bit,
  "PlannedEndDateIsEditable" bit,
  "CanAddComment" bit,
  "CanAddServiceRequest" bit,
  "CanAddAttachment" bit,
  "ServiceRequestDescription" long varchar ) 
begin
  /*
2016-09-02 RJM Addded @Base64Encode
2017-03-08 RJM added OfficeCodeDisplay CHAR(128) to results
2017-12-13 RJM Added permissions after OfficeCodeDisplay
2018-01-23 JLD E-03645 B-17478 Added CanAddAttachment
2018-08-14 JHM Added ServiceRequestDescription
*/
  call "SRM"."ServiceRequestItemDetails"(@RowId,@Base64Encode)
end