create procedure --RJM
"_SRM"."ServiceRequestsRelatedItems"( 
  in @RowId char(1024) ) 
result( 
  "RowId" char(1024),
  "ServiceRequestId" integer,
  "ServiceRequestParentId" integer,
  "OriginalServiceRequestId" integer,
  "ServiceRequestNestedLevel" tinyint,
  "ServiceRequestExternalId" char(20),
  "ServiceRequestType" char(10),
  "ServiceRequestDate" date,
  "ServiceRequestOriginator" integer,
  "ServiceRequestOriginatorName" char(256),
  "OfficeCodeId" integer,
  "OfficeCode" char(10),
  "AssignedToUserId" integer,
  "AssignedToUserFullName" char(256),
  "ServiceRequestStatus" char(25),
  "ServiceRequestPriority" tinyint,
  "ServiceRequestPriorityDisplay" char(25),
  "ServiceRequestTitle" char(128),
  "ServiceRequestPrelimDueDate" date,
  "ServiceRequestFinalDueDate" date,
  "PlannedStartDate" date,
  "PlannedEndDate" date,
  "PercentComplete" integer,
  "PercentHoursComplete" integer,
  "PercentTimeComplete" integer,
  "EstimatedRemainingHours" numeric(12,2),
  "ActualHoursWorked" numeric(12,2),
  "EstimatedTotalHours" numeric(12,2),
  "MandatoryMinReportDays" integer,
  "TransaltNumber" char(25),
  "TransaltId" integer,
  "PrimaryPOCID" integer,
  "PrimaryPOCName" char(256),
  "PrimaryPOCEmail" varchar(500),
  "PrimaryPOCPhone" char(20),
  "AltPOCID" integer,
  "AltPOCName" char(256),
  "AltPOCEmail" varchar(500),
  "AltPOCPhone" char(20),
  "ServiceRequestDeliverables" long varchar,
  "ServiceRequestCategories" long varchar,
  "ServiceRequestRequiredApprovals" long varchar,
  "ServiceRequestRequiredDetails" long varchar,
  "VesselIds" long varchar,
  "VesselNames" long varchar,
  "ServiceRequestParentExternalId" char(20),
  "OriginalServiceRequestExternalId" char(20),
  "CanEditDescription" bit,
  "CanEditStatus" bit,
  "CanAddSupportItem" bit,
  "CanEditProgress" bit,
  "CanEditAttachment" bit,
  "CanEditMilestones" bit,
  "CanEditUserProfile" bit,
  "CanEditBranchProfile" bit,
  "CanEditTeamSpace" bit,
  "LastMileStone" char(80),
  "ActiveSequenceNumber" tinyint,
  "TotalRows" integer,
  "ServiceRequestDescription" long varchar,
  "WorkItemLibraryId" integer ) 
begin
  /*
2017-03-10 RJM Added     ServiceRequestDescription LONG VARCHAR
2017-12-05 RJM Added WorkItemLibraryId
*/
  call "SRM"."ServiceRequestsRelatedItems"(@RowId)
end