create procedure "_PAV"."AvailabilitiesMainGridAvailabilities"( 
  in @NodeId char(256) default null,
  in @OrderBy char(256) default null,
  in @IsLimited bit default 1 ) 
result( 
  "RowId" char(256),
  "ContractRowId" char(256),
  "ContractId" integer,
  "ContractNumber" char(128),
  "ContractType" char(25),
  "ContractStartDate" date,
  "ContractStartDateIsActual" char(1),
  "ContractEndDate" date,
  "ContractEndDateIsActual" char(1),
  "Status" char(25),
  "ContractEstimated" numeric(15,2),
  "ContractAwarded" numeric(15,2),
  "ContractActual" numeric(15,2),
  "WorkItemId" integer,
  "WITitle" char(128),
  "WINumber" char(25),
  "WICategory" char(25),
  "SWBS" char(10),
  "ContractCanEdit" bit,
  "ContractCanDelete" bit,
  "ContractCanRestore" bit,
  "WorkItemCanReassign" bit,
  "OrderBy" char(256),
  "WorkItemCanEdit" bit,
  "WorkItemCanDelete" bit,
  "ContractIsDeleted" bit,
  "WorkItemIsDeleted" bit,
  "WorkItemCanRestore" bit,
  "SpecificationId" integer,
  "SpecificationFileName" char(256),
  "EstimateId" integer,
  "EstimateFileName" char(256),
  "WorkItemEstimated" numeric(15,2),
  "WorkItemAwarded" numeric(15,2),
  "WorkItemActual" numeric(15,2),
  "HasEstimate" bit,
  "HasSpecification" bit,
  "HasAttachment" bit,
  "VesselId" smallint,
  "TotalRows" integer ) 
begin
  call "PAV"."AvailabilitiesMainGridAvailabilities"(@NodeId,@OrderBy,@IsLimited)
end