create procedure "_PAV"."AvailabilitiesMainGridServiceOrders"( 
  in @NodeId char(256) default null,
  in @OrderBy char(256) default null,
  in @IsLimited bit default 1 ) 
result( 
  "RowId" char(256),
  "VesselId" smallint,
  "VesselName" char(80),
  "ContractId" integer,
  "Number" char(128),
  "ContractType" char(25),
  "Status" char(25),
  "AvailabilityId" integer,
  "Availability" char(128),
  "WorkItemId" integer,
  "Title" char(128),
  "SWBS" char(10),
  "Requisition" char(128),
  "Mods" integer,
  "PurchaseOrder" char(128),
  "StartDate" date,
  "StartDateIsActual" char(1),
  "EndDate" date,
  "EndDateIsActual" char(1),
  "AvailabilityType" char(25),
  "EstimatedCost" numeric(15,2),
  "AwardedCost" numeric(15,2),
  "ActualCost" numeric(15,2),
  "CanEdit" bit,
  "CanDelete" bit,
  "CanRestore" bit,
  "OrderBy" char(256),
  "IsDeleted" bit,
  "SpecificationId" integer,
  "SpecificationFileName" char(256),
  "EstimateId" integer,
  "EstimateFileName" char(256),
  "HasEstimate" bit,
  "HasSpecification" bit,
  "HasAttachment" bit,
  "TotalRows" integer ) 
begin
  call "PAV"."AvailabilitiesMainGridServiceOrders"(@NodeId,@OrderBy,@IsLimited)
end