create procedure "_TAR"."TransaltRequestItemDetails"( 
  in @RowId char(1024),
  in @Action char(10) default null,
  in @IsEncoded bit default null ) 
result( 
  "RowId" char(1024),
  "TitleBarDisplay" char(128),
  "TransaltId" integer,
  "RequestDate" date,
  "VesselClass" char(256),
  "RequestNumber" char(25),
  "TransaltTitle" char(128),
  "TransaltNumber" char(25),
  "TransaltDescription" long varchar,
  "TransaltsType" char(25),
  "SWBS" char(4),
  "Priority" char(25),
  "Category" char(25),
  "ApprovedDate" date,
  "Status" char(25),
  "SourceItem" char(25),
  "AffectedSystem" char(50),
  "EstimatedCost" numeric(15,2),
  "EstimatedGovernmentFurnishedMaterialsCostPerVessel" numeric(15,2),
  "FundingSource" char(25),
  "WorkItemTitle" char(128),
  "WorkItemCategory" char(5),
  "WorkItemNumber" char(25),
  "EstimateId" integer,
  "EstimateFileName" char(256),
  "SpecificationId" integer,
  "SpecificationFileName" char(256),
  "HasSpecification" bit,
  "HasEstimate" bit,
  "WorkItemLibraryId" integer,
  "CanAddTAltRequest" bit,
  "CanAddServiceRequest" bit,
  "CanEditDescription" bit,
  "CanAddSpec" bit,
  "CanEditSpec" bit,
  "CanAddComment" bit,
  "CanAddAttachment" bit,
  "CanEditAttachment" bit,
  "CanVote" bit,
  "NumberOfRelatedItems" integer,
  "NumberExecutionStatus" char(10),
  "NumberOfRevisions" integer,
  "NumberOfCompletionForms" char(10),
  "NumberOfAttachments" integer,
  "ROM" numeric(15,2),
  "DialogTitle" char(50),
  "SWBSTitle" char(128),
  "SystemDescription" char(50),
  "TransaltNumberIsEditable" bit,
  "RequestNumberIsEditable" bit,
  "StatusIsEditable" bit,
  "SourceItemIsEditable" bit,
  "CategoryIsEditable" bit,
  "TransaltTitleIsEditable" bit,
  "RequestDateIsEditable" bit,
  "ApprovedDateIsEditable" bit,
  "PriorityIsEditable" bit,
  "TransaltTypeIsEditable" bit,
  "AffectedSystemIsEditable" bit,
  "SWBSIsEditable" bit,
  "ROMIsEditable" bit,
  "ExecutionPlanCanDelete" bit,
  "ExecutionPlanIsEditable" bit,
  "ExecutionPlanCanAdd" bit,
  "EmailDetailsAreEditable" bit ) 
begin
  if @IsEncoded is null then
    set @IsEncoded = 0
  end if;
  call "TAR"."TransaltRequestItemDetails"(@RowId,@Action,@IsEncoded)
end