create procedure "_PNG"."WorkItemsPartsOrdersGeneral"( 
  in @RowId char(256) ) 
result( 
  "RequiredDeliveryDate" date,
  "FundCode" char(80),
  "WorkItemTitle" char(128),
  "OrderedBy" char(256),
  "OrderedByEmailAddress" char(254),
  "PTDRequired" bit,
  "InspectionRequired" bit,
  "AcceptEquivalent" bit,
  "Priority" integer,
  "WorkItemNumber" char(128),
  "SoleSourceAttached" bit,
  "ShippingLocation" char(128),
  "AddressLineOne" char(128),
  "AddressLineTwo" char(128),
  "AddressLineThree" char(128),
  "City" char(128),
  "StateProvince" char(128),
  "ZipPostalCode" char(15),
  "Country" char(2),
  "PhoneNumber" char(23),
  "Attention" char(256),
  "NoteToBuyer" long varchar,
  "CanEditRequiredDeliveryDate" bit,
  "CanEditFundCode" bit,
  "CanEditWorkItemTitle" bit,
  "CanEditOrderedBy" bit,
  "CanEditOrderedByEmailAddress" bit,
  "CanEditPTDRequired" bit,
  "CanEditInspectionRequired" bit,
  "CanEditAcceptEquivalent" bit,
  "CanEditPriority" bit,
  "CanEditWorkItemNumber" bit,
  "CanEditSoleSourceAttached" bit,
  "CanEditShippingLocation" bit,
  "CanEditAddressLineOne" bit,
  "CanEditAddressLineTwo" bit,
  "CanEditAddressLineThree" bit,
  "CanEditCity" bit,
  "CanEditStateProvince" bit,
  "CanEditZipPostalCode" bit,
  "CanEditCountry" bit,
  "CanEditPhoneNumber" bit,
  "CanEditAttention" bit,
  "CanEditNoteToBuyer" bit,
  "CanEditAttachments" bit,
  "CanImportSources" bit ) 
begin
  call "PNG"."WorkItemsPartsOrdersGeneral"(@RowId)
end