create procedure "_VTL"."DocumentsDownLoadList"()
result( 
  "RowId" char(1024),
  "DocumentId" integer,
  "DocumentTypeId" integer,
  "DocumentType" char(50),
  "FileExtension" char(4),
  "PDF" bit,
  "AUTOCAD" bit,
  "FileSize" char(20),
  "DocumentFileName" char(255),
  "DocumentTitle" char(255),
  "ElectronicCopyExists" bit,
  "HardCopyExists" bit,
  "ITAR" char(1),
  "ITARDisplay" char(259),
  "CreateTimeStamp" timestamp,
  "CreatedByID" integer,
  "CreatedBy" char(256),
  "LastModifiedTimeStamp" timestamp,
  "LastModifiedByID" integer,
  "LastModifiedBy" char(255),
  "DocumentNumber" char(50),
  "DocumentAltNumber" char(50),
  "DocumentNSN" char(50),
  "SearchNumber" char(150),
  "Revision" char(10),
  "RevisionDate" date,
  "DocumentIsCancelled" bit,
  "EquipmentClassificationId" integer,
  "EquipmentClassificationDescription" char(50),
  "BulletinTypeID" integer,
  "BulletinType" char(100),
  "GroupNumber" char(3),
  "GroupDescription" char(100),
  "GroupDisplay" char(106),
  "Sheet" char(4),
  "SRD" bit,
  "Salvage" bit,
  "Design" bit,
  "Change" char(10),
  "TMMA" bit,
  "ManufacturerId" integer,
  "ManufacturerName" char(80),
  "ModelNumbers" char(250),
  "ModelIDs" integer,
  "DocumentRemarks" long varchar,
  "TransAltsAssociated" long varchar,
  "LatestRevision" bit,
  "TotalRows" integer ) 
begin
  call "VTL"."DocumentsDownLoadList"()
end