create procedure "_VTL"."RequestTechManualNumberInsertUpdate"( 
  in @RequestTechManualNumberId integer default null,
  in @RequestedById integer default null,
  in @RequestedByFullName varchar(256) default null,
  in @RequestedByEmail varchar(256) default null,
  in @RequestedByPhone varchar(15) default null,
  in @ExistingManual bit default null,
  in @ExistingManualNum varchar(200) default null,
  in @ContractTMSRNum varchar(200) default null,
  in @CompanyCreatingManual varchar(200) default null,
  in @UIC varchar(200) default null,
  in @ShipApplicabilityId integer default null,
  in @TechManualChange long varchar default null,
  in @RequestTypeInHouse bit default null,
  in @NewTechManualTitle varchar(200) default null,
  in @ManufacturerId integer default null,
  in @FMSPublication_Req bit default null,
  in @EquipmentModel varchar(250) default null,
  in @SerialNumber varchar(200) default null,
  in @DataRightsLimited bit default null,
  in @DistributionLevel varchar(50) default null,
  in @ESTDistributionDate date default null,
  in @PartOfVolumnSet bit default null,
  in @PartOfvolumnSetNum integer default null,
  in @PublicationGroup varchar(50) default null,
  in @ApplicabilityGroup varchar(50) default null,
  in @APL_AEL varchar(200) default null,
  in @SecurityClassification varchar(50) default null,
  in @PublicationDistributionSatement varchar(50) default null,
  in @NIINNumber varchar(50) default null,
  in @Change char(10) default null,
  in @Revision char(10) default null,
  in @RequestTechManualNumberStatusId integer default null,
  in @RequestDomain char(100) default null ) 
result( 
  "Success" bit,
  "ErrorMEssage" long varchar,
  "RequestTechManualNumberId" integer,
  "RowId" char(1024) ) 
begin
  call "VTL"."RequestTechManualNumberInsertUpdate"(
  @RequestTechManualNumberId,
  @RequestedById,
  @RequestedByFullName,
  @RequestedByEmail,
  @RequestedByPhone,
  @ExistingManual,
  @ExistingManualNum,
  @ContractTMSRNum,
  @CompanyCreatingManual,
  @UIC,
  @ShipApplicabilityId,
  @TechManualChange,
  @RequestTypeInHouse,
  @NewTechManualTitle,
  @ManufacturerId,
  @FMSPublication_Req,
  @EquipmentModel,
  @SerialNumber,
  @DataRightsLimited,
  @DistributionLevel,
  @ESTDistributionDate,
  @PartOfVolumnSet,
  @PartOfvolumnSetNum,
  @PublicationGroup,
  @ApplicabilityGroup,
  @APL_AEL,
  @SecurityClassification,
  @PublicationDistributionSatement,
  @NIINNumber,
  @Change,
  @Revision,
  @RequestTechManualNumberStatusId,
  @RequestDomain)
end