create procedure "_VTL"."SearchTransaltRequestItems"( 
  in @SearchText char(512) default null,
  in @VesselClass integer default null ) 
result( 
  "RowId" char(1024),
  "TransaltId" integer,
  "TransaltTitle" char(128),
  "TitleBarDisplay" char(128),
  "TransaltExternalId" char(25),
  "RequestOrTAlt" char(10),
  "TransaltNumber" char(25),
  "TransaltDescription" long varchar,
  "TransaltsType" char(25),
  "SWBS" char(4),
  "Priority" char(25),
  "Category" char(25),
  "ApprovedDate" date,
  "Status" char(25),
  "RequestDate" date,
  "RequestNumber" char(25),
  "EstimatedCost" numeric(15,2),
  "EstimatedGovernmentFurnishedMaterialsCostPerVessel" numeric(15,2),
  "FundingSource" char(25),
  "WorkItemTitle" char(128),
  "WorkItemCategory" char(5),
  "WorkItemNumber" char(25),
  "EstimateId" integer,
  "EstimateFileName" char(256),
  "SpecificationId" integer,
  "SpecificationFileName" char(256),
  "HasSpecification" bit,
  "HasEstimate" bit,
  "WorkItemLibraryId" integer,
  "CanAddTAltRequest" bit,
  "CanAddServiceRequest" bit,
  "CanEditDescription" bit,
  "CanAddSpec" bit,
  "CanEditSpec" bit,
  "CanAddComment" bit,
  "CanAddAttachment" bit,
  "CanEditAttachment" bit,
  "CanVote" bit,
  "TotalRows" integer,
  "CurrentPage" integer,
  "TotalPages" integer ) 
begin
  call "VTL"."SearchTransaltRequestItems"(@SearchText,@VesselClass)
end