create procedure "_VTL"."DocumentsQuickEditSave"( in @RowId char(1024),
  in @DocumentTypeID tinyint default null,
  in @DocumentNumber char(50) default null,
  in @DocumentAltNumber char(50) default null,
  in @GroupNumber char(3) default null,
  in @NSN char(50) default null,
  in @Revision char(10) default null,
  in @Change char(10) default null,
  in @DocumentTitle char(255) default null,
  in @RevisionDate date default null,
  in @ITAR char(1) default null,
  in @Remarks long varchar default null,
  in @ElectronicCopyExists bit default null,
  in @HardCopyExists bit default null,
  in @PhysicalLocation char(255) default null,
  in @ManufacturerId integer default null,
  in @ModelNumberModel char(255) default null,
  in @TransAltAssociated char(255) default null,
  in @DocumentCategories long varchar default null,
  in @VesselsAssociated long varchar default null,
  in @VesselsEquipmentAssociated long varchar default null,
  in @EquipmentClassificationId integer default null,
  in @RelatedDocuments long varchar default null,
  in @RsnElecCopyUnavailId integer default null,
  in @TMMA bit,
  in @SRD bit,
  in @Salvage bit,
  in @Design bit,
  in @PhysicalLocationId integer,
  in @DocumentRecordTypeId integer default null,
  in @SSIC char(20) default null ) 
result( "RowId" char(1024),
  "Success" bit,
  "ErrorMessage" long varchar ) 
begin
  call "VTL"."DocumentsQuickEditSave"(@RowId,
  @DocumentTypeID,
  @DocumentNumber,
  @DocumentAltNumber,
  @GroupNumber,
  @NSN,
  @Revision,
  @Change,
  @DocumentTitle,
  @RevisionDate,
  @ITAR,
  @Remarks,
  @ElectronicCopyExists,
  @HardCopyExists,
  @PhysicalLocation,
  @ManufacturerId,
  @ModelNumberModel,
  @TransAltAssociated,
  @DocumentCategories,
  @VesselsAssociated,
  @VesselsEquipmentAssociated,
  @EquipmentClassificationId,
  @RelatedDocuments,
  @RsnElecCopyUnavailId,
  @TMMA,
  @SRD,
  @Salvage,
  @Design,
  @PhysicalLocationId,
  @DocumentRecordTypeId,
  @SSIC)
end