create procedure "_VTL"."GetDocumentsRelatedItems"( 
  in @VesselClass integer default 0,
  in @OrderBy char(512) default null,
  in @UsePaging bit default 1,
  in @RowsPerPage integer default 500,
  in @PageToDisplay integer default 1,
  in @AllTextSearchString varchar(256) ) 
result( 
  "RowId" char(1024),
  "DocumentId" integer,
  "DocumentTypeId" integer,
  "DocumentType" char(50),
  "FileExtension" char(4),
  "PDF" bit,
  "AUTOCAD" bit,
  "FileSize" char(20),
  "DocumentFileName" char(255),
  "DocumentTitle" char(255),
  "ElectronicCopyExists" bit,
  "HardCopyExists" bit,
  "ITAR" char(1),
  "ITARDisplay" char(259),
  "CreateTimeStamp" timestamp,
  "CreatedByID" integer,
  "CreatedBy" char(256),
  "LastModifiedTimeStamp" timestamp,
  "LastModifiedByID" integer,
  "LastModifiedBy" char(255),
  "DocumentNumber" char(50),
  "DocumentAltNumber" char(50),
  "DocumentNSN" char(50),
  "SearchNumber" char(150),
  "Revision" char(10),
  "RevisionDate" date,
  "DocumentIsCancelled" bit,
  "EquipmentClassificationId" integer,
  "EquipmentClassificationDescription" char(50),
  "BulletinTypeID" integer,
  "BulletinType" char(100),
  "GroupNumber" char(3),
  "GroupDescription" char(100),
  "GroupDisplay" char(106),
  "Sheet" char(4),
  "SRD" bit,
  "Salvage" bit,
  "Design" bit,
  "Change" char(10),
  "TMMA" bit,
  "ManufacturerId" integer,
  "ManufacturerName" char(80),
  "ModelNumbers" char(250),
  "ModelIDs" integer,
  "DocumentRemarks" long varchar,
  "TransAltsAssociated" long varchar,
  "LatestRevision" bit,
  "ShipsAssociated" long varchar,
  "InDownloadList" bit,
  "DocumentIsActive" bit,
  "RsnElecCopyUnavailId" integer,
  "TotalRows" integer,
  "CurrentPage" integer,
  "TotalPages" integer ) 
begin
  call "VTL"."GetDocumentsRelatedItems"(@VesselClass,@OrderBy,@UsePaging,@RowsPerPage,@PageToDisplay,@AllTextSearchString)
end