create procedure "_VTL"."RequestTechManualNumberGrid"( 
  in @RequestTechManualNumberStatusId integer default null,
  in @RequestTechManualNumberId integer default null,
  in @RequestingUserId integer default null ) 
result( 
  "RequestTechManualNumberId" integer,
  "RequestedById" integer,
  "RequestedOn" date,
  "RequestedByFullName" varchar(256),
  "RequestedByEmail" varchar(256),
  "RequestedByPhone" varchar(15),
  "ExistingManual" bit,
  "ExistingManualNum" varchar(200),
  "ContractTMSRNum" varchar(200),
  "CompanyCreatingManual" varchar(200),
  "UIC" varchar(200),
  "ShipApplicabilityId" integer,
  "TechManualChange" long varchar,
  "RequestTypeInHouse" bit,
  "NewTechManualTitle" varchar(200),
  "ManufacturerId" integer,
  "Manufacturer" char(80),
  "FMSPublication_Req" bit,
  "EquipmentModelId" integer,
  "EquipmentModel" varchar(250),
  "SerialNumber" varchar(200),
  "DataRightsLimited" bit,
  "DistributionLevelId" integer,
  "DistributionLevel" varchar(50),
  "ESTDistributionDate" date,
  "PartOfVolumnSet" bit,
  "PartOfvolumnSetNum" integer,
  "PublicationGroupId" integer,
  "PublicationGroup" varchar(50),
  "ApplicabilityGroupId" integer,
  "ApplicabilityGroup" varchar(50),
  "APL_AEL" varchar(200),
  "SecurityClassificationId" integer,
  "SecurityClassification" varchar(50),
  "PublicationDistributionStatementId" char(1),
  "PublicationDistributionStatement" varchar(50),
  "RequestTechManualNumberStatusId" integer,
  "RequestTechManualNumberStatus" varchar(50),
  "NIINNumber" varchar(50),
  "Change" char(10),
  "NumberStatus" varchar(10),
  "Revision" char(10),
  "RowId" char(1024) ) 
begin
  call "VTL"."RequestTechManualNumberGrid"(@RequestTechManualNumberStatusId,@RequestTechManualNumberId,@RequestingUserId)
end