create procedure "_SWA"."VesselMetrics"( 
  in @VesselClassId integer ) 
result( 
  "VesselName" char(80),
  "FY1" integer,
  "Approved1" integer,
  "Completed1" integer,
  "Completion1" integer,
  "Outstanding1" integer,
  "Planned1" integer,
  "Unplanned1" integer,
  "MissingReports1" integer,
  "FY2" integer,
  "Approved2" integer,
  "Completed2" integer,
  "Completion2" integer,
  "Outstanding2" integer,
  "Planned2" integer,
  "Unplanned2" integer,
  "MissingReports2" integer,
  "FY3" integer,
  "Approved3" integer,
  "Completed3" integer,
  "Completion3" integer,
  "Outstanding3" integer,
  "Planned3" integer,
  "Unplanned3" integer,
  "MissingReports3" integer,
  "FY4" integer,
  "Approved4" integer,
  "Completed4" integer,
  "Completion4" integer,
  "Outstanding4" integer,
  "Planned4" integer,
  "Unplanned4" integer,
  "MissingReports4" integer,
  "FY5" integer,
  "Approved5" integer,
  "Completed5" integer,
  "Completion5" integer,
  "Outstanding5" integer,
  "Planned5" integer,
  "Unplanned5" integer,
  "MissingReports5" integer ) 
begin
  call "SWA"."VesselMetrics"(@VesselClassId)
end